### ISSUE TITLE
冒昧的问下sessionStorage与dcc.Store有啥区别

### ISSUE THREAD

**Issue by sylvoslee** [CNFeffery/feffery-utils-components#1]

**Comment by CNFeffery** [comment]
@sylvoslee 你在那个dash交流群里没，fuc.sessionStorage是支持监听其他方式执行的sessionStorage变化的，比如在浏览器端回调里通过原生js模拟更新了指定key的sessionStorage的值，我在fuc.sessionStorage也是可以监听到这个变化并触发dash回调的
