### ISSUE TITLE
FefferyCountup样式丢失

### ISSUE THREAD

**Issue by yzcheung** [CNFeffery/feffery-utils-components#75]
![before](https://github.com/user-attachments/assets/f3a655d4-5413-45c6-b241-8df82764ba81)
![after](https://github.com/user-attachments/assets/884c6ef0-6c86-44e7-9ad2-732788316be9)

图一feffery_utils_components==0.2.0rc0
图二feffery_utils_components==0.2.0rc22

Countup内的数字样式丢失，无法继承父节点的样式

**Comment by CNFeffery** [comment]
最新预发布版本已修复
