### ISSUE TITLE
 在Output中使用了allow_duplicate=True模式时，FefferyTopProgress无法正确监听组件参数

### ISSUE THREAD

**Issue by insistence** [CNFeffery/feffery-utils-components#8]
FefferyTopProgress监听模式为include，监听属性以动态增删标签页的items为例，当items使用了allow_duplicate=True模式时，FefferyTopProgress无法正确监听

**Comment by CNFeffery** [comment]
@insistence 才看到，可以提供一个迷你的可复现示例吗

**Comment by CNFeffery** [comment]
就我测试的这个例子而言，没有遇到问题：

```python
import dash
import time
from dash import html
import feffery_utils_components.alias as fuc
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = fuc.TopProgress(
    html.Div(
        [
            html.Button(
                '测试1',
                id='button1'
            ),
            html.Button(
                '测试2',
                id='button2'
            ),
            html.Div(
                id='demo-output'
            )
        ],
        style={
            'padding': 50
        }
    )
)

@app.callback(
    Output('demo-output', 'children', allow_duplicate=True),
    Input('button1', 'n_clicks'),
    prevent_initial_call=True
)
def demo1(n_clicks):

    time.sleep(2)

    return '测试1：%s' % n_clicks


@app.callback(
    Output('demo-output', 'children'),
    Input('button2', 'n_clicks'),
    prevent_initial_call=True
)
def demo2(n_clicks):

    time.sleep(2)

    return '测试2：%s' % n_clicks


if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by insistence** [comment]
import dash
import time
from dash import html
import feffery_utils_components as fuc
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = fuc.FefferyTopProgress(
    html.Div(
        [
            html.Button(
                '测试1',
                id='button1'
            ),
            html.Button(
                '测试2',
                id='button2'
            ),
            html.Div(
                id='demo-output'
            )
        ],
        style={
            'padding': 50
        }
    ),
    listenPropsMode='include',
    includeProps=['demo-output.children']
)

@app.callback(
    Output('demo-output', 'children', allow_duplicate=True),
    Input('button1', 'n_clicks'),
    prevent_initial_call=True
)
def demo1(n_clicks):

    time.sleep(2)

    return '测试1：%s' % n_clicks


@app.callback(
    Output('demo-output', 'children', allow_duplicate=True),
    Input('button2', 'n_clicks'),
    prevent_initial_call=True
)
def demo2(n_clicks):

    time.sleep(2)

    return '测试2：%s' % n_clicks


if __name__ == '__main__':
    app.run(debug=True)
改成这样FefferyTopProgress就不生效了，使用include模式且output均使用了allow_duplicate=True模式

**Comment by insistence** [comment]
`import dash
import time
from dash import html
import feffery_utils_components as fuc
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = fuc.FefferyTopProgress(
    html.Div(
        [
            html.Button(
                '测试1',
                id='button1'
            ),
            html.Button(
                '测试2',
                id='button2'
            ),
            html.Div(
                id='demo-output'
            )
        ],
        style={
            'padding': 50
        }
    ),
    listenPropsMode='include',
    includeProps=['demo-output.children']
)

@app.callback(
    Output('demo-output', 'children', allow_duplicate=True),
    Input('button1', 'n_clicks'),
    prevent_initial_call=True
)
def demo1(n_clicks):

    time.sleep(2)

    return '测试1：%s' % n_clicks


@app.callback(
    Output('demo-output', 'children', allow_duplicate=True),
    Input('button2', 'n_clicks'),
    prevent_initial_call=True
)
def demo2(n_clicks):

    time.sleep(2)

    return '测试2：%s' % n_clicks


if __name__ == '__main__':
    app.run(debug=True)`

改成这样FefferyTopProgress就不生效了，使用include模式且output均使用allow_duplicate=True模式

**Comment by insistence** [comment]
```
import dash
import time
from dash import html
import feffery_utils_components as fuc
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = fuc.FefferyTopProgress(
    html.Div(
        [
            html.Button(
                '测试1',
                id='button1'
            ),
            html.Button(
                '测试2',
                id='button2'
            ),
            html.Div(
                id='demo-output'
            )
        ],
        style={
            'padding': 50
        }
    ),
    listenPropsMode='include',
    includeProps=['demo-output.children']
)

@app.callback(
    Output('demo-output', 'children', allow_duplicate=True),
    Input('button1', 'n_clicks'),
    prevent_initial_call=True
)
def demo1(n_clicks):

    time.sleep(2)

    return '测试1：%s' % n_clicks


@app.callback(
    Output('demo-output', 'children', allow_duplicate=True),
    Input('button2', 'n_clicks'),
    prevent_initial_call=True
)
def demo2(n_clicks):

    time.sleep(2)

    return '测试2：%s' % n_clicks


if __name__ == '__main__':
    app.run(debug=True)
```
改成这样FefferyTopProgress就不生效了，使用include模式且output均使用allow_duplicate=True模式

**Comment by CNFeffery** [comment]
`fuc` >= 0.2.0b1版本已修复
